vbar=(▁ ▂ ▃ ▄ ▅ ▆ ▇ █)
hbar=(▏ ▎ ▍ ▌ ▋ ▊ ▉ █)
shadow=(░ ▒ ▓)
cell_arc=(╭ ╮ ╯ ╰)
diagonals=(╱ ╲ ╳)
line_solid=(─ ━ │ ┃)
line_double=(═ ║)
line_dash=(╌ ╍ ╎ ╏ ┄ ┅ ┆ ┇ ┈ ┉ ┊ ┋)
box=(┌ ┍ ┎ ┏ ┐ ┑ ┒ ┓ └ ┕ ┖ ┗ ┘ ┙ ┚ ┛├ ┝ ┞ ┟ ┠ ┡ ┢ ┣ ┤ ┥ ┦ ┧ ┨ ┩ ┪ ┫ ┬ ┭ ┮ ┯ ┰ ┱ ┲ ┳ ┴ ┵ ┶ ┷ ┸ ┹ ┺ ┻ ┼ ┽ ┾ ┿ ╀ ╁ ╂ ╃ ╄ ╅ ╆ ╇ ╈ ╉ ╊ ╋)
line_half=(╴ ╵ ╶ ╷ ╸ ╹ ╺ ╻ ╼ ╽ ╾ ╿)
quadrant_squares=(▖ ▗ ▘ ▝ ▞ ▚ ▙ ▛ ▜ ▟)

## Block elements
# ▀ UPPER HALF BLOCK
# ▁ LOWER ONE EIGHTH BLOCK
# ▂ LOWER ONE QUARTER BLOCK
# ▃ LOWER THREE EIGHTHS BLOCK
# ▄ LOWER HALF BLOCK
# ▅ LOWER FIVE EIGHTHS BLOCK
# ▆ LOWER THREE QUARTERS BLOCK
# ▇ LOWER SEVEN EIGHTHS BLOCK
# █ FULL BLOCK
# ▉ LEFT SEVEN EIGHTHS BLOCK
# ▊ LEFT THREE QUARTERS BLOCK
# ▋ LEFT FIVE EIGHTHS BLOCK
# ▌ LEFT HALF BLOCK
# ▍ LEFT THREE EIGHTHS BLOCK
# ▎ LEFT ONE QUARTER BLOCK
# ▏ LEFT ONE EIGHTH BLOCK
# ▐ RIGHT HALF BLOCK

## Shade characters
# ░ LIGHT SHADE
# ▒ MEDIUM SHADE
# ▓ DARK SHADE

## Block elements
# ▔ UPPER ONE EIGHTH BLOCK
# ▕ RIGHT ONE EIGHTH BLOCK

## Terminal graphic characters
# ▖ QUADRANT LOWER LEFT
# ▗ QUADRANT LOWER RIGHT
# ▘ QUADRANT UPPER LEFT
# ▝ QUADRANT UPPER RIGHT
# ▞ QUADRANT UPPER RIGHT AND LOWER LEFT
# ▚ QUADRANT UPPER LEFT AND LOWER RIGHT
# ▙ QUADRANT UPPER LEFT AND LOWER LEFT AND LOWER RIGHT
# ▛ QUADRANT UPPER LEFT AND UPPER RIGHT AND LOWER LEFT
# ▜ QUADRANT UPPER LEFT AND UPPER RIGHT AND LOWER RIGHT
# ▟ QUADRANT UPPER RIGHT AND LOWER LEFT AND LOWER RIGHT

## Light and heavy solid lines
# ─ LIGHT HORIZONTAL
# ━ HEAVY HORIZONTAL
# │ LIGHT VERTICAL
# ┃ HEAVY VERTICAL

## Double lines
# ═ DOUBLE HORIZONTAL
# ║ DOUBLE VERTICAL

## Light and heavy dashed lines
# ╌ LIGHT DOUBLE DASH HORIZONTAL
# ╍ HEAVY DOUBLE DASH HORIZONTAL
# ╎ LIGHT DOUBLE DASH VERTICAL
# ╏ HEAVY DOUBLE DASH VERTICAL
# ┄ LIGHT TRIPLE DASH HORIZONTAL
# ┅ HEAVY TRIPLE DASH HORIZONTAL
# ┆ LIGHT TRIPLE DASH VERTICAL
# ┇ HEAVY TRIPLE DASH VERTICAL
# ┈ LIGHT QUADRUPLE DASH HORIZONTAL
# ┉ HEAVY QUADRUPLE DASH HORIZONTAL
# ┊ LIGHT QUADRUPLE DASH VERTICAL
# ┋ HEAVY QUADRUPLE DASH VERTICAL

## Light and heavy half lines
# ╴ LIGHT LEFT
# ╵ LIGHT UP
# ╶ LIGHT RIGHT
# ╷ LIGHT DOWN
# ╸ HEAVY LEFT
# ╹ HEAVY UP
# ╺ HEAVY RIGHT
# ╻ HEAVY DOWN

## Light and heavy line box components
# ┌ LIGHT DOWN AND RIGHT
# ┍ DOWN LIGHT AND RIGHT HEAVY
# ┎ DOWN HEAVY AND RIGHT LIGHT
# ┏ HEAVY DOWN AND RIGHT
# ┐ LIGHT DOWN AND LEFT
# ┑ DOWN LIGHT AND LEFT HEAVY
# ┒ DOWN HEAVY AND LEFT LIGHT
# ┓ HEAVY DOWN AND LEFT
# └ LIGHT UP AND RIGHT
# ┕ UP LIGHT AND RIGHT HEAVY
# ┖ UP HEAVY AND RIGHT LIGHT
# ┗ HEAVY UP AND RIGHT
# ┘ LIGHT UP AND LEFT
# ┙ UP LIGHT AND LEFT HEAVY
# ┚ UP HEAVY AND LEFT LIGHT
# ┛ HEAVY UP AND LEFT

## |-
# ├ LIGHT VERTICAL AND RIGHT
# ┝ VERTICAL LIGHT AND RIGHT HEAVY
# ┞ UP HEAVY AND RIGHT DOWN LIGHT
# ┟ DOWN HEAVY AND RIGHT UP LIGHT
# ┠ VERTICAL HEAVY AND RIGHT LIGHT
# ┡ DOWN LIGHT AND RIGHT UP HEAVY
# ┢ UP LIGHT AND RIGHT DOWN HEAVY
# ┣ HEAVY VERTICAL AND RIGHT

## -|
# ┤ LIGHT VERTICAL AND LEFT
# ┥ VERTICAL LIGHT AND LEFT HEAVY
# ┦ UP HEAVY AND LEFT DOWN LIGHT
# ┧ DOWN HEAVY AND LEFT UP LIGHT
# ┨ VERTICAL HEAVY AND LEFT LIGHT
# ┩ DOWN LIGHT AND LEFT UP HEAVY
# ┪ UP LIGHT AND LEFT DOWN HEAVY
# ┫ HEAVY VERTICAL AND LEFT

## T
# ┬ LIGHT DOWN AND HORIZONTAL
# ┭ LEFT HEAVY AND RIGHT DOWN LIGHT
# ┮ RIGHT HEAVY AND LEFT DOWN LIGHT
# ┯ DOWN LIGHT AND HORIZONTAL HEAVY
# ┰ DOWN HEAVY AND HORIZONTAL LIGHT
# ┱ RIGHT LIGHT AND LEFT DOWN HEAVY
# ┲ LEFT LIGHT AND RIGHT DOWN HEAVY
# ┳ HEAVY DOWN AND HORIZONTAL

## inverted T
# ┴ LIGHT UP AND HORIZONTAL
# ┵ LEFT HEAVY AND RIGHT UP LIGHT
# ┶ RIGHT HEAVY AND LEFT UP LIGHT
# ┷ UP LIGHT AND HORIZONTAL HEAVY
# ┸ UP HEAVY AND HORIZONTAL LIGHT
# ┹ RIGHT LIGHT AND LEFT UP HEAVY
# ┺ LEFT LIGHT AND RIGHT UP HEAVY
# ┻ HEAVY UP AND HORIZONTAL

## +
# ┼ LIGHT VERTICAL AND HORIZONTAL
# ┽ LEFT HEAVY AND RIGHT VERTICAL LIGHT
# ┾ RIGHT HEAVY AND LEFT VERTICAL LIGHT
# ┿ VERTICAL LIGHT AND HORIZONTAL HEAVY
## Mixed light and heavy lines
# ╼ LIGHT LEFT AND HEAVYRIGHT
# ╽ LIGHT UP AND HEAVY DOWN
# ╾ HEAVY LEFT AND LIGHTRIGHT
# ╿ HEAVY UP AND LIGHT DOWN
# ╀ UP HEAVY AND DOWN HORIZONTAL LIGHT
# ╁ DOWN HEAVY AND UP HORIZONTAL LIGHT
# ╂ VERTICAL HEAVY AND HORIZONTAL LIGHT
# ╃ LEFT UP HEAVY AND RIGHTDOWN LIGHT
# ╄ RIGHT UP HEAVY AND LEFTDOWN LIGHT
# ╅ LEFT DOWN HEAVY AND RIGHT UP LIGHT
# ╆ RIGHT DOWN HEAVY AND LEFT UP LIGHT
# ╇ DOWN LIGHT AND UP HORIZONTAL HEAVY
# ╈ UP LIGHT AND DOWN HORIZONTAL HEAVY
# ╉ RIGHT LIGHT AND LEFT VERTICAL HEAVY
# ╊ LEFT LIGHT AND RIGHT VERTICAL HEAVY
# ╋ HEAVY VERTICAL AND HORIZONTAL

# ╣ DOUBLE VERTICAL AND LEFT
# ╤ DOWN SINGLE AND HORIZONTAL DOUBLE
# ╥ DOWN DOUBLE AND HORIZONTAL SINGLE
# ╦ DOUBLE DOWN AND HORIZONTAL
# ╧ UP SINGLE AND HORIZONTALDOUBLE
# ╨ UP DOUBLE AND HORIZONTAL SINGLE
# ╩ DOUBLE UP AND HORIZONTAL
# ╪ VERTICAL SINGLE AND HORIZONTAL DOUBLE
# ╫ VERTICAL DOUBLE AND HORIZONTAL SINGLE
# ╬ DOUBLE VERTICAL AND HORIZONTAL

## Character cell arcs
# ╭ LIGHT ARC DOWN AND RIGHT
# ╮ LIGHT ARC DOWN AND LEFT
# ╯ LIGHT ARC UP AND LEFT
# ╰ LIGHT ARC UP AND RIGHT

## Character cell diagonals
# ╱ LIGHT DIAGONAL UPPERRIGHT TO LOWER LEFT
# ╲ LIGHT DIAGONAL UPPER LEFTTO LOWER RIGHT
# ╳ LIGHT DIAGONAL CROSS

## Light and double line box components
# ╒ DOWN SINGLE AND RIGHT DOUBLE
# ╓ DOWN DOUBLE AND RIGHT SINGLE
# ╔ DOUBLE DOWN AND RIGHT
# ╕ DOWN SINGLE AND LEFT DOUBLE
# ╖ DOWN DOUBLE AND LEFT SINGLE
# ╗ DOUBLE DOWN AND LEFT
# ╘ UP SINGLE AND RIGHT DOUBLE
# ╙ UP DOUBLE AND RIGHT SINGLE
# ╚ DOUBLE UP AND RIGHT
# ╛ UP SINGLE AND LEFT DOUBLE
# ╜ UP DOUBLE AND LEFT SINGLE
# ╝ DOUBLE UP AND LEFT
# ╞ VERTICAL SINGLE AND RIGHT DOUBLE
# ╟ VERTICAL DOUBLE AND RIGHT SINGLE
# ╠ DOUBLE VERTICAL AND RIGHT
# ╡ VERTICAL SINGLE AND LEFT DOUBLE
# ╢ VERTICAL DOUBLE AND LEFT SINGLE