#!/usr/bin/env bash
# ─ LIGHT HORIZONTAL
# │ LIGHT VERTICAL
# ╭ LIGHT ARC DOWN AND RIGHT
# ╮ LIGHT ARC DOWN AND LEFT
# ╯ LIGHT ARC UP AND LEFT
# ╰ LIGHT ARC UP AND RIGHT

case $current in
  ─) next=;;
# │ LIGHT VERTICAL
# ╭ LIGHT ARC DOWN AND RIGHT
# ╮ LIGHT ARC DOWN AND LEFT
# ╯ LIGHT ARC UP AND LEFT
# ╰ LIGHT ARC UP AND RIGHT